### ISSUE TITLE
Wish simulator bug

### ISSUE THREAD

**Issue by kumihyuu** [Wolfteam/GenshinDb#8]
Hi, I've downloaded your app and it's amazing. The only problem I have is with the wish simulator.
I don't have any "x" button to click and proceed with. I can't reduce the size of page or anything so I'm blocked. There is an image as reference to explain better
![Screenshot_20210131-150756](https://user-images.githubusercontent.com/78307940/106386751-d1dced00-63d6-11eb-982d-65e36ea8dcca.png)

**Comment by Wolfteam** [comment]
Hiho, thanks for the bug report, could you tell me what resolution you
phone has and which model are you using?

Also, if you open the map page, does it work correctly for you?

**Comment by kumihyuu** [comment]
Thank you for the quick reply.
I have a Huawei p10 lite, 5.2 or 1920x1080 pixel.
Map works wonderful

**Comment by Wolfteam** [comment]
> Thank you for the quick reply.
> I have a Huawei p10 lite, 5.2 or 1920x1080 pixel.
> Map works wonderful

Not sure why is being displayed like that (since your device is a big one and with a high resolution), anyway, I just released a beta of the app that contains a small workaround to the play store (it should be up in 2 hrs +-), so please try it and let me know if it fixes the problem

To join the beta program, open the play store app, and go to the genshindb page, and you should see a section called "beta program" or something like that, you click the join button, wait for 5 minutes, go back to the play store, and you will see an update.

**Comment by kumihyuu** [comment]
Disinstalled, refreshed the phone and intalled again the app and now it works! Thanx anyways
